package com.yrgo.dataaccess;

import com.yrgo.domain.Call;
import com.yrgo.domain.Customer;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private static final String INSERT_SQL =
            "INSERT INTO Customer (customerId, companyName, email, telephone, notes) VALUES (?, ?, ?, ?, ?)";
    private static final String DELETE_SQL = "DELETE FROM Customer WHERE customerId = ?";
    private static final String UPDATE_SQL =
            "UPDATE Customer SET companyName = ?, email = ?, telephone = ?, notes = ? WHERE customerId = ?";
    private static final String GET_BY_ID_SQL = "SELECT * FROM Customer WHERE customerId = ?";
    private static final String GET_BY_NAME_SQL = "SELECT * FROM Customer WHERE companyName = ?";
    private static final String GET_ALL_SQL = "SELECT * FROM Customer";
    private static final String ADD_CALL_SQL =
            "INSERT INTO CustomerCall (timeAndDate, notes, customerId) VALUES (?, ?, ?)";
    private static final String GET_CALL_SQL = "SELECT * FROM CustomerCall WHERE customerId = ?";

    private final JdbcTemplate template;

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template) {
        this.template = template;
        try {
            createTables();
        } catch (Exception e) {
            System.err.println("Table already exists");
        }
    }

    private void createTables()	{
        try{
            this.template.update("CREATE TABLE IF NOT EXISTS Customer (" +
                    "customerId VARCHAR(50) PRIMARY KEY," +
                    "companyName VARCHAR(100) NOT NULL," +
                    "email VARCHAR(100)," +
                    "telephone VARCHAR(15)," +
                    "notes VARCHAR(255));");

            this.template.update("CREATE TABLE IF NOT EXISTS CustomerCall (" +
                    "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "timeAndDate TIMESTAMP," +
                    "notes VARCHAR(255)," +
                    "customerId VARCHAR(50)," +
                    "FOREIGN KEY (customerId) REFERENCES Customer(customerId) ON DELETE CASCADE);");
        }catch (org.springframework.jdbc.BadSqlGrammarException e){
            System.out.println("Something went wrong with SQl");
        }
    }

    @Override
    public void create(Customer customer) {
        template.update(INSERT_SQL, customer.getCustomerId(), customer.getCompanyName(), customer.getEmail(),
                        customer.getTelephone(), customer.getNotes());
    }

    @Override
    public Customer getById(String customerId) throws RecordNotFoundException {
        return template.queryForObject(
                GET_BY_ID_SQL,
                new Object[]{customerId},
                (rs, rowNum) -> new Customer(
                        rs.getString("customerId"),
                        rs.getString("companyName"),
                        rs.getString("email"),
                        rs.getString("telephone"),
                        rs.getString("notes")
                )
        );
    }

    @Override
    public List<Customer> getByName(String name) {
        return template.query(
                GET_BY_NAME_SQL,
                new Object[]{name},
                (rs, rowNum) -> new Customer(
                        rs.getString("customerId"),
                        rs.getString("companyName"),
                        rs.getString("email"),
                        rs.getString("telephone"),
                        rs.getString("notes")
                )
        );
    }

    @Override
    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        template.update(UPDATE_SQL, customerToUpdate.getCompanyName(), customerToUpdate.getEmail(),
                customerToUpdate.getTelephone(), customerToUpdate.getNotes(), customerToUpdate.getCustomerId());
    }

    @Override
    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        template.update(DELETE_SQL, oldCustomer.getCustomerId());
    }

    @Override
    public List<Customer> getAllCustomers() {
        return template.query(
                GET_ALL_SQL,
                (rs, rowNum) -> new Customer(
                        rs.getString("customerId"),
                        rs.getString("companyName"),
                        rs.getString("email"),
                        rs.getString("telephone"),
                        rs.getString("notes")
                )
        );
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        Customer customer = template.queryForObject(
                GET_BY_ID_SQL,
                new Object[]{customerId},
                (rs, rowNum) -> new Customer(
                        rs.getString("customerId"),
                        rs.getString("companyName"),
                        rs.getString("email"),
                        rs.getString("telephone"),
                        rs.getString("notes")
                )
        );

        List<Call> calls = template.query(
                GET_CALL_SQL,
                new Object[]{customerId},
                (rs, rowNum) -> new Call(
                        rs.getString("notes"),
                        rs.getTimestamp("timeAndDate")
                )
        );

        if (customer != null) {
            customer.setCalls(calls);
        }
        return customer;
    }

    @Override
    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        template.update(
                ADD_CALL_SQL,
                new Object[]{newCall.getTimeAndDate(), newCall.getNotes(), customerId}
        );
    }
}
